---@alias Trunks.CompletionType "filepath" | "subcommand" | "branch"
---@type table<string, Trunks.CompletionType>
return {
    add = "filepath",
    archive = "filepath",
    bisect = "subcommand",
    bundle = "subcommand",
    checkout = "branch",
    diff = "filepath",
    grep = "filepath",
    maintenance = "subcommand",
    merge = "branch",
    mv = "filepath",
    notes = "subcommand",
    rebase = "branch",
    reflog = "subcommand",
    remote = "subcommand",
    rerere = "subcommand",
    restore = "filepath",
    revert = "branch",
    rm = "filepath",
    stash = "subcommand",
    switch = "branch",
    worktree = "subcommand",
}
