# TODO: (you) - To enable this workflow, you need to provide a LUAROCKS_API_KEY
#
# References:
#   https://github.com/nvim-neorocks/sample-luarocks-plugin?tab=readme-ov-file#publishing-to-luarocks
#
name: Release To LuaRocks

on:
  push:
    tags:
      - "v*"

jobs:
  luarocks-upload:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
